### ISSUE TITLE
Setup file unable to run

### ISSUE THREAD

**Issue by doesthismatter12312** [leycec/fsnrnue#11]
When I ran the installer (both the one click installer and the command line installer), the game couldn't find fate.exe.
![Screenshot_20210612_232229](https://user-images.githubusercontent.com/49215755/121794332-c2787680-cbf6-11eb-9cb8-2c52492102df.png)

Going into the directory, the script file seems to not have generated fate.exe. It also did not generate the folder that houses fate.exe. The extraction worked fine, and the patches seem to be installed correctly (I think), but the only executable outside of the three folders that contain the 3 routes is the setup file.
![Screenshot_20210612_232537](https://user-images.githubusercontent.com/49215755/121794372-0b302f80-cbf7-11eb-8f74-98b652d66066.png)

When I tried to run the setup file, wine was unable to execute it. 
![Screenshot_20210612_232711](https://user-images.githubusercontent.com/49215755/121794402-46326300-cbf7-11eb-983c-b08467e3f105.png)

 Any help would be greatly appreciated!

**Comment by charttrakarn0784** [comment]
I got the same problem.

**Comment by leycec** [comment]
*...uhohs.* At least those adorable folder thumbnails for the three F/SN routes momentarily brightened an otherwise dark, depressing issue that threatens to consume my evening.

The installer should be creating a `drive_c/Program Files/Fate／stay night[Realta Nua] Ultimate Edition/` subdirectory containing the main `Fate.exe` executable, but that doesn't appear to be happening anymore. `</sigh>`

I suspect Lutris 0.5.8.3 broke something critical here. Let's have a deeper look then, shall we? :mag:

**Comment by leycec** [comment]
**Ohsnap.** It's [actually WINE 6.x at fault here](https://forum.winehq.org/viewtopic.php?f=8&t=35192), moe-bros.

WINE 6.5.2 is purportedly the last WINE version to *not* be hit by this issue. I can personally verify that both WINE 6.6.1 and WINE 6.10 are affected, despite [upstream WINE developers claiming they resolved this in WINE 6.7](https://bugs.winehq.org/show_bug.cgi?id=50978). They didn't. We suffer for their negligence.

We now need to explicitly restrict F/SN to a specific WINE version known to play well with F/SN's antiquated 32-bit assumptions. Fortunately, that's trivial. Unfortunately, it requires my time and I am sleepy and I just want to play *Dragon Quest XI S* but what can you do? `</sigh>`

**Comment by leycec** [comment]
**Bwaha!** Summarily fixed. We now force usage of WINE 6.1.3 for F/SN, which we can all agree is pretty lame but better than letting newer versions of WINE indiscriminately break everything.

Thanks for the detailed report and those swag screenshots, @doesthismatter12312, and the confirmation, @charttrakarn0784. All's well that ends with a brute-force kludge. :smile:

**Comment by denppa** [comment]
> **Bwaha!** Summarily fixed. We now force usage of WINE 6.1.3 for F/SN, which we can all agree is pretty lame but better than letting newer versions of WINE indiscriminately break everything.
> 
> Thanks for the detailed report and those swag screenshots, @doesthismatter12312, and the confirmation, @charttrakarn0784. All's well that ends with a brute-force kludge. smile

So I am on arch, I suppose in order for the force wine to work I need the wine 6.1.3 installed for it to work right? Since this error still happened to me.

**Comment by leycec** [comment]
In theory, Lutris itself should automatically download and locally install WINE 6.1.3 *before* running the F/SN Ultimate Edition installer. If that isn't happening, you might be using our old installer that still has this bug.

Are you trying to **[install F/SN from the Lutris website?](https://lutris.net/games/fatestay-night)** If so, please don't do that for the moment. The F/SN installer hosted on the Lutris website has yet to be patched with this fix. Instead:

1. Manually download [the F/SN installer hosted at this repository](https://raw.githubusercontent.com/leycec/fsnrnue/master/lutris/fate-stay-night-realta-nua-ultimate-edition.yml). It's just a single YAML file, so stuff it anywhere you like! :stuck_out_tongue: 
1. Manually run that installer from the command line:

```
lutris -i fate-stay-night-realta-nua-ultimate-edition.yml
```

I'm on Gentoo, so I feel your pain with respect to installing specific WINE versions. But that shouldn't be necessary here, because Lutris should internally automate this for you now. <sup>*...should*</sup>

If none of the above resolves this for you, feel free to either open a new issue here for me or [chime in on issue #12, where other horrible stuff possibly related to what you're seeing is happening](https://github.com/leycec/fsnrnue/issues/12).
