### ISSUE TITLE
Background Flickering

### ISSUE THREAD

**Issue by denppa** [leycec/fsnrnue#13]
Game runs fine in the original aspect ratio if launched in full screen. But if you switch to windowed and back to full screen rom there, the black space will have flickering of random things.

Same thing happens if it is launched in windowed format and you enlarge it to be full screen, shit happens.

https://i.imgur.com/BCWmnvj.png

See that cancer on the right hand side?

Any idea why and how to fix?

**Comment by leycec** [comment]
...total cancer confirmed.

This is almost certainly a **WINE + Vulkan + DXVK** issue, which means this *probably* can be fixed on your end. Since WINE and DXVK versions are the easiest to tweak, I'd start there. Specifically, incrementally downgrade first WINE and then DXVK until the issue disappears – which it eventually should, unless it's actually an artifact of the underlying Vulkan implementation in your mostly closed-source GPU that you have no control over, in which case that would suck.

Since I can't replicate this myself, it's hard to offer a concrete insta-fix here. [Downgrading WINE versions in Lutris is probably the simplest](https://forums.lutris.net/t/installing-a-previous-wine-runner-for-a-game/11517/2), so I might start there. F/SN is so painfully old now that it *should* run under literally any WINE ≤ 6.6.1 version.

If you find a better WINE version than the one we currently force in our YAML installer (i.e., WINE 6.1.3), **please let us know.** I'll happily switch out WINE 6.1.3 for something proven to work better.

Thanks again for all the intrepid work. On behalf of Holy Grail War Servants everywhere, I humbly apologize for all the troubles you've had getting this up and running. I promise that joy and copious buckets of Shiro's blood are nearly around the corner. *Rin would approve!* :mage_woman:

**Comment by denppa** [comment]
So I don't think this is something within a linux noob'x expertise anymore.

I know that launching it in full screen and then not going to windowed and back to full manually negates the problem so I am more than happy to have that.

I guess if not everyone is getting it I can just suffer on my own. Thank you dev for providing help with your knowledge of code.

**Comment by leycec** [comment]
**Oh!** I just remembered something relevant. I absolutely don't blame you for abandoning the good cause, 'cause nobody got time for debugging low-level WINE artifacting. But...

The Ultimate Edition comes with a ton of menu options – one of which enables a fan-made "Wide Mode."  **That option should be disabled.** It's problematic under Windows and only gets worse under Linux. Specifically:

* Show the Ultimate Edition menu by moving the mouse to the top of the F/SN window.
* Ensure that *Display* -> *Aspect Ratio* -> *Standard* is checked. *Wide* should not be checked.

Lastly, I advise playing with the flowchart PDF that comes with the game and going for all of the Bad Ends. You'll see what I mean when you get there. <sup>*heh*</sup>

**Comment by denppa** [comment]
> Ensure that Display -> Aspect Ratio -> Standard is checked. Wide should not be checked.

Indeed I am playing in the original aspect ratio.

> Lastly, I advise playing with the flowchart PDF that comes with the game and going for all of the Bad Ends. 
You'll see what I mean when you get there. heh

Hmm I think I needa search a bit to find where that is.

**Comment by leycec** [comment]
> Indeed I am playing in the original aspect ratio.

...this saddens me.

> Hmm I think I needa search a bit to find where that is.

**Finally.** A thing I can fix for you. F/SN so desperately needs a flowchart for sane playthroughs that it actually comes bundled with one at `{insert_lutris_install_dir_here}/drive_c/Program\ Files/Fate／stay night[Realta Nua] Ultimate Edition/Flowchart.PDF`. [Okular](https://okular.kde.org) guarantees happiness here.

Welcome to the Taiga Dojo. *We do hope you enjoy your stay.* :tiger: :tiger: :tiger:

**Comment by denppa** [comment]
> ...this saddens me.

Wasn't it a common census to play in the 4:3 instead of the fan made wide mode? Why does it saddens you?

**Comment by leycec** [comment]
Oh, it saddens me just because I'd wanted to help you. Since you're already in 4:3, I'm helpless and can do nothing. I like playing the [white knight niceguy Gary Stu](https://en.wikipedia.org/wiki/Mary_Sue) on GitHub. Helping people is fun, guys! <sup>*who knew*</sup>

Have a great time with F/SN. As always, let me know if you'd like Lutris installers for anything related and I'll see what I can cook up. :factory_worker:
