### ISSUE TITLE
Installer uses Wine version not present in Lutris

### ISSUE THREAD

**Issue by jtyuill** [leycec/fsnrnue#26]
When using the Lutris online installer, the install fails as Wine 6.14.3 is not present in Lutris anymore for whatever reason. To workaround this I downloaded 6.14.4 from the "Manage wine versions" window and renamed the runner folder to 6.14.3 and the install worked as expected. I'm not a dev so I don't actually know how it works but I'd assume this can be fixed by changing the default wine version the installer runs on

**Comment by OverlordMarkus** [comment]
Going to add what I already told mnbnd over on the subreddit.

While I managed to install the VN in the end as well, I solved the issue by changing the wine version in the offline installer (line 56) from 6.21.5 to the current 6.21.6. I also noticed that the online installer still uses version 6.14.3 which is also no longer supported.

**Comment by kaasknak** [comment]
Oh boy. WINE is really causing a mess here. Unfortunately a lot of wine version are fundamentally broken with FSN so we have to pin a version. I will adjust the script first thing tomorrow. 

@leycec do you happen to know something about the online installer not being synchronised with the repo?

**Comment by leycec** [comment]
*...heh.* This is all my fault, of course. We pinned WINE to this older obsolete version, because WINE had an ugly string of "questionable" releases that fundamentally broke F/SN. This was good. But that version no longer exists. So, this is now bad.

I've immediately unpinned WINE in commit d20087f. Our F/SN installer yet again permissively supports all possible WINE versions. You may commence rejoicing. Naturally, I haven't actually tested this. Would someone mind doing that?

@kaasknak: If this is tested to actually work, would you mind updating [our installer stub on the Lutris homepage with this unpinned variant](https://lutris.net/games/fatestay-night)? It goes without saying that you are amazing. Ilya deserves you.

Lastly, **I'm deeply indebted to everyone here.** I kinda lack time to sufficiently maintain this installer anymore – but still happy to lend a helping hand for critically broken meta-issues like this. Fist bumps all around. :fist_left:

**Comment by OverlordMarkus** [comment]
@leycec So, I did as you asked and tested the new offline installer. The installer itself started properly and ran through as usual.

Unfortunately, after completing, the Fate Stay Night icon in Lutris is a white block and when launching it I get the error message:
`This game has no executable set. The install process didn't finish properly.`

I tried it in two different virtualbox machines, Pop and Ubuntu. There is also no protocol if I click on "show protocol".

**Comment by kaasknak** [comment]
> @kaasknak: If this is tested to actually work, would you mind updating [our installer stub on the Lutris homepage with this unpinned variant](https://lutris.net/games/fatestay-night)? It goes without saying that you are amazing. Ilya deserves you.

Tested it and it worked under ubuntu 20.04. It didn't default to wine 7.0 which is newer and stable though so that is weird.
Now it should only cause problems when people are running an outdated version of the developers branch (please let them not be doing that).

I have uploaded the new one to lutris but it is awaiting moderator review. I hope it trickles down eventually.

> Unfortunately, after completing, the Fate Stay Night icon in Lutris is a white block and when launching it I get the error message:
This game has no executable set. The install process didn't finish properly. 

This means patching failed. Patches are held by google and are subject to data limits and not under our control. Instructions on how to fix it can be found [here](https://github.com/leycec/fsnrnue#okay-i-am-indeed-seeing-this-exception-i-think).

**Comment by leycec** [comment]
Thanks so much, @kaasknak! You're a true friend of the eternal burning fire. TYPEMOON moe is life. Life is TYPEMOON moe. :fire: :new_moon: :fire:
