### ISSUE TITLE
Setup is not completed because of a missing file

### ISSUE THREAD

**Issue by Snudle** [leycec/fsnrnue#5]
Thank you very much for giving this file.

I have a problem dowloading the files through the setup application because it always tells me that "Error: [Errno 2] No such file or directory: 'C:\\Users\\Kevin\\OneDrive\\Skrivebord\\Fate／Stay Night\\bgimage.xp3'".
I have no idea how to fix this. An image below should show you how it looks on my screen. This is after choosing my configurations and choosing file locations.

![image](https://user-images.githubusercontent.com/71715872/93898595-a8f36f80-fcf3-11ea-897e-319092271b33.png)

**Comment by leycec** [comment]
**Fascinating...** and horrifying! Well, *that's* a new one. Although I have yet to hit this one myself, this [thankfully appears to be a common issue for Windows users](https://forums.nrvnqsr.com/showthread.php/8229-Fate-Stay-Night-Realta-Nua-Ultimate-Edition?p=3020448&viewfull=1#post3020448).

The core issue here is that you've installed *Fate/Stay Night* to a non-standard directory – in this case, `C:\Users\Kevin\OneDrive\Skrivebord\Fate／Stay Night\`. Of course, that's not quite right. Instead, the Ultimate Edition installer expects you to install *Fate/Stay Night* to the standard `C:\Program Files (x86)\Fate／stay night[Realta Nua] -Fate-\` directory.

Our [Linux-specific Lutris installer](https://github.com/leycec/fsnrnue/blob/master/lutris/fate-stay-night-realta-nua-ultimate-edition.yml) already guarantees this, which suggests you're installing under Windows. Is that right? If so *and* if you're still having issues, please instead [post a comment begging for help to the Ultimate Edition thread at the Beast's Lair](https://forums.nrvnqsr.com/showthread.php/8229-Fate-Stay-Night-Realta-Nua-Ultimate-Edition/page93) – the official discussion forum for the original Windows version of the Ultimate Edition installer.

Thanks for the detailed bug report, @Snudle. Since this is probably a Windows rather than Linux issue, I'm closing this with apologies. Of course, do feel to reopen this if that was in error.

**Comment by leycec** [comment]
To avoid this sort of understandable confusion in the future, I've significantly revised [the preamble of our `README.md` documentation](https://github.com/leycec/fsnrnue#fatestay-night-r%C3%A9alta-nua-ultimate-edition-for-linux). Notably, we now prominently warn that:

> ⚠️

> This repository does *not* officially host **Windows** installers for
> *Fate/stay night \[Réalta Nua\] Ultimate Edition*. If you are
> a **Windows** user and currently having issues under **Windows**, please
> direct bug reports to the upstream forum discussion at the
> Beast's Lair. Thanks – and sorry for the confusion! 😅

**Comment by Snudle** [comment]
Thank you very much, I eill tryon the forum on Beast's Lair. And yes, I am on windows
