### ISSUE TITLE
The game does not start via Lutris

### ISSUE THREAD

**Issue by CavaleriOmar** [leycec/fsnrnue#6]
Before exposing the problem, it is necessary to thank the existence of the possibility offered to be able to read the visual novel on Linux ... in my case EndeavourOS (it is an almost pure Arch, it has only one netinstaller with GUI and only one repo of different).

Speaking of the problem in question, neither the launcher created in the menu nor the one present in Lutris, allow the start of the novel. Now, I don't know if it's due to some setting error (the one in the fairies wizard, where I only selected "no explicit scenes") and if I accidentally touched something on that screen, but at every start attempt, it doesn't absolutely nothing happens.

**Comment by leycec** [comment]
**Fascinating...** and horrifying! I must admit this is the first startup issue we've had and that I myself sadly can't replicate this, which complicates my life. If you wouldn't mind running Lutris from a command-line terminal with the following command, perhaps we can isolate the underlying cause:

```
command lutris &>error.out
```

Let that run for a few minutes. Then, drag-and-drop the `error.out` text file created by that command in your next response to this GitHub issue. With any luck (and more than a little black `grep` magic), that'll give us enough hard details to spin off some sort of a hotfix for you.

Also: *yay, EndeavourOS!* Arch and everything Arch-like rocks.

**Comment by CavaleriOmar** [comment]
At this command (command lutris &>error.out)... this is the output... i've waited 10 minutes:

```
[omar@EndeavourOS ~]$ command lutris &>error.out
[omar@EndeavourOS ~]$
```

Also, trying to start it after I restarted the pc, it gave this screen (not given to the first attempts):
[https://i.imgur.com/rtv2mdD.png](url)

If it helps, I also copied the log file given by Lutris for the FSN:

```
lutris-wrapper: Fate/Stay Night
Running /home/omar/.local/share/lutris/runners/wine/lutris-5.7-10-x86_64/bin/wine /home/omar/Games/fatestay-night/drive_c/Program Files/Fate／stay night[Realta Nua] Ultimate Edition/Fate.exe
Initial process has started with pid 12859
Game is considered started.


16:22:46 iinfojData HaFfile://./c/program files/fate^stay night[realta nua] ultimate edition/savedata/




16:22:46 (info) Total 0 file(s) found, 0 file(s) activated. (0ms)


16:22:46 iinfojCPU #0 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:no  AVX2:no  FMA3:no  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Celeron(R) CPU N3350 @ 1.10GHz]  CPUID(1)/EAX=000506C9 CPUID(1)/EBX=00200800
16:22:46 iinfojCPU #1 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:no  AVX2:no  FMA3:no  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Celeron(R) CPU N3350 @ 1.10GHz]  CPUID(1)/EAX=000506C9 CPUID(1)/EBX=04200800










16:22:47 (info) Total 29642 file(s) found, 29642 file(s) activated. (148ms)













16:22:47 (info) Total 34776 file(s) found, 34765 file(s) activated. (77ms)



16:22:47 (info) Total 35791 file(s) found, 35780 file(s) activated. (70ms)
16:22:47 OS : Windows 7 6.1.3505 Service Pack 1 (Win32)
16:22:47 KAG : 3.25 beta 10 TYPE-MOON customized
16:22:47 Kirikiri : 1.4.0.8



16:22:47 ==== An exception occured at initialize.tjs(214)[(top level script) global], VM ip = 694 ====
16:22:47 -- Disassembled VM code --
16:22:47 #(214) if(Storages.isExistentStorage("Config.tjs"))
16:22:47 00000687 const %1, *70	// *70 = (string)"Config.tjs"
16:22:47 00000690 gpd %2, %-2.*71	// *71 = (string)"Storages"
16:22:47 00000694 calld %3, %2.*72(%1)	// *72 = (string)"isExistentStorage"
16:22:47 -- Register dump --
16:22:47 %-7=(object)(object 0x00FA1778:0x00FA1778)  %-6=(string)"type"  %-5=(int)28  %-4=(void)
16:22:47 %-3=(void)  %-2=(object)(object 0x0032F684:0x00000000)
16:22:47 %-1=(object)(object 0x00F800E0:0x00F800E0)  %0=(void)  %1=(string)"Config.tjs"
16:22:47 %2=(object)(object 0x00F9DB28:0x00000000)  %3=(void)
16:22:47 %4=(object)(object 0x00FA6968:0x00000000)  %5=(object)(object 0x00FAA650:0x00000000)
16:22:47 %6=(string)"Win32"  %7=(string)")"  %8=(object)(object 0x00FA6968:0x00000000)
16:22:47 ---------------------------------------------------------------------------------------------

16:22:47 trace : startup.tjs(27)[(top level script) global] <-- startup




Game is considered exited.
Initial process has exited.
All monitored processes have exited.
Exit with returncode 256
```

PS: the dual core's 1.1 GHz is nominal only. Usually the dual core stays at 1.7-2.1 GHz in normal use (peaking at 2.4 GHz).

**Comment by leycec** [comment]
Thanks a bunch for the voluminous reply, @CavaleriOmar. I suspect we're almost there. <sup>*Ilya be praised!*</sup>

Given the suspicious strings `patch.xp3` in the GUI error and `"An exception occured at initialize.tjs"` in the Lutris output you helpfully shared, this is **[almost certainly a patch corruption issue](https://github.com/leycec/fsnrnue#how-to-resolve-script-exception-raised-errors-at-startup)**. Specifically, your `patch.xp3` file (i.e., the core mandatory *Ultimate Edition* patch required by all other non-core optional *Ultimate Edition* patches) doesn't appear to have downloaded properly for you. Due to the unreliable third-party website hosting these humongous patches, patch corruption is a sadly common issue that we can't do very much about at the moment.

But we *can* do something about your specific issue. Would you mind [following our FAQ instructions for resolving this and trying again](https://github.com/leycec/fsnrnue#how-to-resolve-script-exception-raised-errors-at-startup)? With any luck, you're almost there. :crossed_fingers:

**Comment by leycec** [comment]
**Boom!** I've [significantly revised our FAQ to more explicitly address this issue](https://github.com/leycec/fsnrnue/#faq), including the exact screenshot you generously captured and donated above. Ilya thanks you. :teddy_bear:

**Comment by CavaleriOmar** [comment]
I performed the bad patch replacement ... so, now Fate pops up, for like 1 second and then fails.

Here is the log (only the last part) given by Lutris:

```
info: Game: Fate.exe
info: DXVK: v1.7.1-2-g743f309
info: Built-in extension providers:
info: Win32 WSI
info: OpenVR
warn: OpenVR: Failed to locate module
info: Required Vulkan extension VK_KHR_surface not supported
terminate called after throwing an instance of 'dxvk :: DxvkError'
Game is considered exited.
Initial process has exited.
All monitored processes have exited.
Exit with returncode 768
```

**Comment by leycec** [comment]
**Excellent!** Great work. Now you're *really* almost there. Are you familiar with [Vulkan](https://en.wikipedia.org/wiki/Vulkan_(API))? Basically, Vulkan is the official replacement for [OpenGL](https://en.wikipedia.org/wiki/OpenGL), a popular cross-platform GPU-accelerated 3D rendering API. So, Vulkan = OpenGL 2.0. That's good.

[The DXVK acronym](https://github.com/doitsujin/dxvk) mentioned in the above log is a related Vulkan-based technology. Basically, DXVK is a Linux-specific translation layer that internally converts Windows-specific DirectX 9, 10, and 11 GPU logic into equivalent Vulkan logic. That's also good.

The `"warn: OpenVR: Failed to locate module"` line is safely ignorable. That just means you don't have a virtual reality (VR) headset connected, which is fine. VR's awesome and all, but that's not really what we're going for here.

The `"info: Required Vulkan extension VK_KHR_surface not supported"` line is where your troubles start. **Your Vulkan installation is broken.** That's bad, because it means that you won't be run any GPU-accelerated Vulkan games. Thankfully, *Fate/stay night* is so old that it runs on decades-old potato PCs and doesn't really benefit GPU acceleration at all.

You have two options here:

* (*Recommended*) **Disable Vulkan for *Fate/stay night*.** This is the easy way:
  1. Run Lutris.
  1. Right-click the *Fate/stay night* icon.
  1. Click the *Configure* menu item.
  1. Click the *Runner options* tab.
  1. Disable the *Enable DXVK/VKD3D* setting.
* **Fix your broken Vulkan/DXVK installation.** This is the hard way, but you probably want to do this eventually *anyway.* Instructions for properly installing and configuring Vulkan and DXVK vary by platform. In your case, you'll want EndeavourOS instructions. Since EndeavourOS is Arch-based, the easiest way to get Vulkan and DXVK up and running would probably be to:
  1. Follow [the Vulkan installation instructions at the Arch Wiki](https://wiki.archlinux.org/index.php/Vulkan#Installation).
  1. Follow [the Wine installation instructions at the Arch Wiki](https://wiki.archlinux.org/index.php/wine#Installation). **Note: install `wine-staging` rather than `wine`.** Always use Wine Staging, which is the bleeding-edge version of Wine that provides DXVK. Never use standard Wine, which is the obsolete version of Wine that provides literally nothing.
  1. Watch [this YouTube video walking you through DXVK configuration under Lutris with Wine Staging](https://forums.lutris.net/t/how-to-setup-dxvk-on-lutris/1704).

In any case, either of those should work for you. Thanks for bearing with this insanity. Let me know how everything goes in the end. If you finally get this up and running, please close out this issue. *Yay!* :wink:

**Comment by CavaleriOmar** [comment]
Thanks for the detail. I fixed everything (I disabled that setting ... and
while I was there I installed the "dxvk-bin" package from aur)

So, it's all OK <https://i.imgur.com/0q9HKT6.png>

Il giorno ven 2 ott 2020 alle ore 21:06 Cecil Curry <
notifications@github.com> ha scritto:

**Comment by leycec** [comment]
**Awesome.** So glad that worked out for you. I've also [updated our FAQ with a new Vulkan/DXVK section hopefully resolving that issue for anyone else who hits it too](https://github.com/leycec/fsnrnue/#i-see-something-about-vulkan-and-dxvk-in-those-logs-i-think). You were invaluably helpful, @CavaleriOmar!

You might also be interested in *another* visual novel-related project I'm working on behind the scenes: a Lutris installer for the [recently released fan-authored native Linux port](https://forums.fuwanovel.net/topic/23163-linux-port-now-released-ao-no-kanata-no-four-rythm-linux-port-18-patch-for-nintendo-switch/?do=findComment&comment=522629) of **[Ao no Kanata (Aokana) no Four Rhythm: Across the Blue, beyond the sky, into the firmament](https://vndb.org/v12849)**, a highly-acclaimed [shounen chuuni visual novel](https://forums.fuwanovel.net/topic/1820-chuuni-what-is-this-genre) that shares a number of genre tags with *Fate/stay night* if you really squint at them. If so, I'll ping you when it's out.

If not, no worries! Enjoy the fateful ride. *Ultimate Blade Works,* in particular, is one bullet hell of a route. :crossed_swords:

**Comment by leycec** [comment]
*Aaaaaaand...* the [initial *Aokana* repository](https://github.com/leycec/aokana-linux) is now live. **Boom!** :boom:
